# TESTRUN akses di port 81
# nginX php-fpm nodejs supervisord 1 container
version: '3'

services:

  base-test:
    image: ${DOCKERHUB_USER}/${BASE_IMAGE_REPO}:${BASE_IMAGE_TAG}
    container_name: ${COMPOSE_PROJECT_NAME}_${BASE_IMAGE_TAG}_TESTRUN
    restart: always
    ports:
      - 81:80
#    volumes:
#      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
